export enum Mutations {
    SAVE_POKEMONS_TO_STORE = 'SAVE_POKEMONS_TO_STORE',
    SAVE_TYPES_TO_STORE = 'SAVE_TYPES_TO_STORE',
    SAVE_POKEMONS_BY_TYPE_TO_STORE = 'SAVE_POKEMONS_BY_TYPE_TO_STORE',
    SAVE_POKEMON_INFO_TO_STORE = 'SAVE_POKEMON_INFO_TO_STORE',
    SAVE_SELECTED_TYPE_TO_STORE = 'SAVE_SELECTED_TYPE_TO_STORE',
}